### ISSUE TITLE
Should support ignore one line of code

### ISSUE THREAD

**Issue by fallenleavesguy** [soda-x/postcss-plugin-px2rem#24]
For example:

```scss
body {
  // @px2rem ignore-next-line
  font-size: 16px;
}
```
